name: Deploy Backend
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            echo "⚙️ Pulling and Reloading Backend..."
            cd /var/www/sarvatirthamayi_site/backend
            git fetch --all
            git reset --hard origin/main
            npm install
            
            # Zero-downtime reload
            pm2 reload all
            
            echo "✅ Backend Deployment Completely Successful! (Zero downtime)"